Abhidip_demo/config/routes.rb
AbhidipDemo::Application.routes.draw do
 resources :users do 
      resources :posts
 end

root :to => 'users#index'

end

Abhidip_demo/app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :title, :body
end

Abhidip_demo/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,:dependent => :destroy
  attr_accessible :user_name, :email, :roll, :age, :dept,:contact_no
  validates  :email, :presence => true
  validates_length_of :contact_no,:minimum=>8,:maximum=>10
  validates :email,:uniqueness => true
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]+\z/i
  before_create do |user|
  user.user_name = user.user_name.capitalize
  end
  before_update do |user|
  user.user_name = user.user_name.capitalize
  end
  
  before_validation :replace
 
  protected
  def replace
    if user_name.nil?
      self.user_name =email unless email.nil?
    end
    
  end
  
    
end

Abhidip_demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
def new
@post=Post.new
end

def create
user=User.find(params[:user_id])
post=user.posts.create(params[:post])
redirect_to user_path(user)
end
def index
  @user =User.find(params[:user_id])
  @posts=@user.posts.find(:all)
  
end
def show
 
  @user=User.find(params[:user_id])
  @post=@user.posts.find(params[:id])
  
end
def edit
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
end

def update
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
@post.update_attributes(params[:post])
@post.save!
redirect_to user_post_path(@user)
end
def destroy
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
@post.destroy
redirect_to user_posts_path(@user)
end
end

Abhidip_demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
	@users=User.all
end
def new
	@user=User.new
end
def create
    @user=User.create(params[:user])
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to users_path
    else
      render 'new'
    end
  end 
def show
  @user=User.find(params[:id])
end
def edit
  @user=User.find(params[:id])
end
def update
user=User.find(params[:id])
user.update_attributes(params[:user])
user.save!
redirect_to users_path
end
def destroy
 user=User.find(params[:id])
 user.destroy
 redirect_to users_path
end
end

Abhidip_demo/app/helpers/posts_helper.rb
module PostsHelper
end

Abhidip_demo/app/views/_shared/_footer.html.erb
<footer id="footer">

<p style="font-size:12px;background-color:#CBE3E8"><i>All copyrights reserved @RayAbhi...</i></p>
</footer>

Abhidip_demo/app/views/_shared/_header.html.erb
<header class="clearfix">
  <p style="font-size:25px;background-color:#BDB2B2" id="header"><i><u>Welcome to PostHub.com</u>...</i></p>
<ul id="navigation">
          <li><a>About Us..</a></li>
          <li><a><%= link_to "Help",    '#' %></a></li>
          <li><a><%= link_to "Home",    users_path %></a></li>
        </ul>
</header>

Abhidip_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AbhidipDemo</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render '_shared/header' %>
<%= yield %>
<hr>
     <%= render '_shared/footer' %>
</body>
</html>

Abhidip_demo/app/views/posts/edit.html.erb
<html>
<%=form_for @post,:url=>user_post_path(@user) do |f|%>
<u><i><%=f.label :title%></i></u>
<%=f.text_field :title%><br>
<br>
<u><i><%=f.label :description%><br>
<%=f.text_area :description%></i></u>
<%= f.submit%>
<%end%>

</html>

Abhidip_demo/app/views/posts/index.html.erb
<%@posts.each do |post|%>
Title:<%=post.title%>
<%=link_to "Show Post..",user_post_path(@user,post)%>
<br>
Description:<%=post.description%><br>

<hr>

<%end%>

Abhidip_demo/app/views/posts/new.html.erb
<%=form_for @post,:url=>user_posts_path do |f|%>
<i><u><%=f.label :title%></u></i>
<%=f.text_field :title%><br>
<br>
<i><u><%=f.label :description%></u></i><br>
<%=f.text_area :description%>
<%= f.submit%>
<%end%>

Abhidip_demo/app/views/posts/show.html.erb
Title:<%=@post.title%>

<br>
Description:<%=@post.description%><br>
<%=link_to "Delete post",user_post_path(@user,@post),:method=>:delete%>
<%=link_to "Edit post",edit_user_post_path(@user,@post)%>
<hr>

Abhidip_demo/app/views/users/_form.html.erb
<%=form_for @user do |f|%>
<%=f.label :user_name%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.text_field :user_name%><br>
<%=f.label :email%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.text_field :email%><br>
<%=f.label :dept%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.text_field :dept%><br>
<%=f.label :roll%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.text_field :roll%><br>
<%=f.label :age%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.text_field :age%><br>
<%=f.label :contact_no%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<%=f.text_field :contact_no%><br>
<hr>
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%=f.submit%>

<%end%>

Abhidip_demo/app/views/users/edit.html.erb
<html>
<i><u>Edit User Here..</u>:--</i>
<%= render :partial => "form" %>

</html>

Abhidip_demo/app/views/users/index.html.erb
<%@users.each do |u|%>
<hr>
Name:<%=u.user_name%>&nbsp;&nbsp;<a><%=link_to "Show", user_path(u)%>
</a><br>
Email:<%=u.email%>&nbsp;&nbsp;
<hr><br>
<%end%>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a><%=link_to "*Create New User*",new_user_path%></a>

Abhidip_demo/app/views/users/new.html.erb
<html>
<i><u>New User Informations..</u>:--</i>
<%= render :partial => "form" %>

</html>

Abhidip_demo/app/views/users/show.html.erb
<html>

Name:&nbsp;&nbsp;&nbsp;<%=@user.user_name%>&nbsp;&nbsp;&nbsp;

<a><%=link_to "Post",new_user_post_path(@user)%></a>
<a><%=link_to "See Posts...",user_posts_path(@user)%></a><br>
Email:&nbsp;&nbsp;&nbsp;<%=@user.email%><br>
Roll:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@user.roll%><br>
Dept.:&nbsp;&nbsp;&nbsp;<%=@user.dept%><br>
Age:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@user.age%><br>
Contact-no:&nbsp;&nbsp;<%=@user.contact_no%><br>
<a><%= link_to "Home",users_path%></a>
<a><%= link_to "Edit",edit_user_path(@user)%></a>
<a><%=link_to "delete User", user_path(@user), :method=>:delete %></a>
</html>